---
title: "Track Remdesivir Literature"
date: 2020-04-15 15:50:42
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path('Remdesivir.html'))})
---

# Remdesivir

The keywords used here are:
Remdesivir, GS-5734, GS-441524, adenosine

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('../R_Functions/Topic_hub_functions.R')
library("readr")
library("ggplot2")
library("kableExtra")
topic <- 'Remdesivir'
```

```{r load_data, include=FALSE}
# Locate most recent file for this topic
data_file <- topicCheck(topic)

# Load the data
topic_data <- read_tsv(data_file)
```
## Number of Related Papers

```{r pressure, echo=FALSE}
p <- ggplot(topic_data, aes(x=DateAdded)) + 
  geom_histogram(bins = as.numeric(difftime(Sys.Date(), as.Date("2020-03-20"),
                                            units="days"))) + 
  labs(y = "Count", x = "Date, 2020", 
       title = paste("Number of Papers on", topic, "Added by CDC"),
       subtitle = "CDC COVID-19 tracking began on March 20, 2020") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) 

print(p)
```

## Potentially Relevant Papers

```{r printTSV, echo=FALSE}
knitr::kable(topic_data[,c("DateAdded", "DOI", "Title", "Journal/Publisher",
                           "Issue", "Reviewers", "PRs")]) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```
